### ISSUE TITLE
Create Typescript definitions for DefinitelyTyped

### ISSUE THREAD

**Issue by webwizrd** [lhkbob/eve-swagger-js#76]
Please add Typescript definitions for eve-swagger to: https://github.com/DefinitelyTyped/DefinitelyTyped
so it can be consumed in TypeScript.

**Comment by lhkbob** [comment]
I have actually been updating the source to be directly in TypeScript, so the next release will provide typings directly without needing a separate dependency to an `@types/eve-swagger`.  

The next release is still a ways out because it's being updated to the newest ESI (from 0.4 to 0.6, so there's a fair bit to add), and I'm trying to overhaul the token management system and provide utilities for accessing multiple resources at once.

However, if you depend directly on the current master with a git URL in your package.json file, you will be able to consume a TypeScript API that is very similar to the API that is currently described in the JSDoc.  The main changes have been in how you get an API instance and the configuration parameters.  See src/index.ts for details.
